# Generated by Django 3.2.8 on 2021-11-13 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=100)),
                ('deadline', models.CharField(max_length=100)),
                ('if_fast', models.BooleanField(blank=True, choices=[(0, 'Normal'), (1, 'As soon as possible')], default=0, null=True)),
                ('task_priority', models.CharField(blank=True, choices=[('Critical', 'Critical'), ('High', 'High'), ('Normal', 'Normal'), ('Low', 'Low'), ('Very Low', 'Very Low')], default='Normal', max_length=100)),
                ('ticket_status', models.CharField(choices=[('Open', 'Open'), ('Resolved', 'Resolved'), ('Closed', 'Closed'), ('Duplicate', 'Duplicate')], default='Open', max_length=100)),
                ('short_description', models.CharField(max_length=1000)),
                ('long_description', models.CharField(max_length=1000)),
                ('market_geography', models.CharField(max_length=100)),
                ('language_choices', models.CharField(choices=[('English', 'English'), ('Russian', 'Russian')], max_length=100)),
                ('comments', models.CharField(blank=True, max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
